### ISSUE TITLE
Wakatime throws an error when trying to enter the API key the first time

### ISSUE THREAD

**Issue by michaelaflores** [wakatime/WakaTime.novaextension#6]
Upon installing Nova on a new M1 MacBook Air and installing WakaTime, attempting to enter the API key presented an error: the file could not be found. I saw another issue #3 that was identical, and their workaround of creating the file in the home directory worked. However I think WakaTime should handle this case correctly.

**Comment by alanhamlett** [comment]
Creating the `~/.wakatime.cfg` config file worked? I thought that was fixed with 2.0.1.

**Comment by michaelaflores** [comment]
Yup creating it worked! I opened this just to bring visibility to the issue still occurring. My WakaTime in Nova says "2.0.0, 3 months ago" by the way, although I just installed it a couple of days ago. Perhaps the update isn't showing up in Nova yet?

**Comment by alanhamlett** [comment]
Yea, looks like it's not detecting the update. I've contacted Nova about it.

**Comment by alanhamlett** [comment]
Actually, I already emailed Nova support about this 3 months ago. Maybe they'll notice it with [a tweet](https://twitter.com/WakaTime/status/1374780889670950912).

**Comment by michaelaflores** [comment]
@alanhamlett I've found their support times to be problematic as a user as well... hoping they get this resolved soon! At any rate, once that new version is out I'll definitely try to reproduce this there.

**Comment by alanhamlett** [comment]
We just needed to click a menu item inside Nova... 

<img width="289" alt="Screen Shot 2021-03-24 at 1 13 14 PM" src="https://user-images.githubusercontent.com/522344/112377236-b7badf00-8ca2-11eb-8d3f-b818a98344b4.png">

The new version is published to the extension library now.
